### ISSUE TITLE
Write requirements.txt

### ISSUE THREAD

**Issue by soilSpoon** [smooth-lee/investing-calendar#1]
Python 패키지들은 일반적으로 `requirements.txt`를 사용하여 관리합니다.

**Comment by smooth-lee** [comment]
이 프로젝트는 패키지 2개만으로 사용이 가능하여 README.md 참고하셔서 설치하는게 더 빠릅니다. 

프로젝트의 규모가 커지면 사용해보도록 하겠습니다.
